project:
  type: book
  output-dir: docs

book:
  title: "Butterfly Monitoring and Analyses"
  date: today
  author: 
  - name: Reto Schmucki
    orcid: 0000-0003-3064-7553
    email: retoschm@ceh.ac.uk
    affiliations:
      - name: UK Centre for Ecology & Hydrology
        address: Maclean Building Benson lane
        city: Crowmarsh Gilford, Wallingford
        state: Oxfordshire
        postal-code: OX10 8BB
  # - name: Dylan Carbone
  #   email: dylcar@ceh.ac.uk
  #   affiliations:
  #     - name: UK Centre for Ecology & Hydrology
  #       address: Maclean Building Benson lane
  #       city: Crowmarsh Gilford, Wallingford
  #       state: Oxfordshire
  #       postal-code: OX10 8BB

  search: true
  repo-url: https://github.com/RetoSchmucki/Butterfly-Monitoring-Analyses
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - part: "Counting Butterflies"
      chapters: 
      -  Chapters/CountingButterflies/Butterfly_monitoring.qmd 
    - part: "From Counts to Flight Curves"
      chapters:
      - Chapters/FromCountsToFlightCurves/data_analyses_methods.qmd
      - Chapters/FromCountsToFlightCurves/butterfly_counts.qmd
      - Chapters/FromCountsToFlightCurves/gam_method.qmd
      - Chapters/FromCountsToFlightCurves/bivoltine_species.qmd
    - part: "Butterfly Trends"
      chapters:
      - Chapters/FromCountsToFlightCurves/trend_simulation.qmd
    - part: "Bibliography"
      chapters:
      - Chapters/Bibliography/references.qmd
  
bibliography: references.bib
highlight-style: pygments

execute:
  cache: false

format:
  html:
    theme: cosmo
    linkcolor: '#008b8b'
    code-block-bg: '#F5F5F2'
    code-block-border-left: true
    code-fold: true

  pdf:
    documentclass: book
    linkcolor: '#008b8b'
    code-block-bg: '#F5F5F2'
    code-block-border-left: true
    geometry:
      - top=30mm
      - left=25mm
      - right=20mm
      - heightrounded
