project:
  type: book
  output-dir: docs

book:
  title: "Butterfly Monitoring Analyses"
  date: today
  author: 
  - name: Reto Schmucki
    orcid: 0000-0003-3064-7553
    email: retoschm@ceh.ac.uk
    affiliations:
      - name: UK Centre for Ecology & Hydrology
        address: Maclean Building Benson lane
        city: Crowmarsh Gilford, Wallingford
        state: Oxfordshire
        postal-code: OX10 8BB
  - name: Dylan Carbone
    email: dylcar@ceh.ac.uk
    affiliations:
      - name: UK Centre for Ecology & Hydrology
        address: Maclean Building Benson lane
        city: Crowmarsh Gilford, Wallingford
        state: Oxfordshire
        postal-code: OX10 8BB

  search: true
  repo-url: https://github.com/RetoSchmucki/Butterfly-Monitoring-Analyses
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - part: "Counting Butterflies"
      chapters: 
      -  Butterfly_monitoring.qmd 
    - part: "From Counts to FLight Curves"
      chapters:
      - butterfly_counts.qmd
  # - part: "Bibliography"
  #   - references.qmd
  
bibliography: references.bib
highlight-style: pygments

execute:
  cache: true

format:
  html:
    theme: cosmo
    linkcolor: 'darkcyan'
    code-block-bg: '#F5F5F2'
    code-block-border-left: true

  pdf:
    documentclass: book
    linkcolor: 'darkcyan'
    code-block-bg: '#F5F5F2'
    code-block-border-left: true
